name: publish-dev
on:
  push:
    branches:
      - 'next'
    paths:
      - 'source/**'
      - '.github/workflows/publish-dev.yml'

  workflow_dispatch:

jobs:
  publish-dev:
    name: publish docs/dev
    runs-on: ubuntu-latest
    env:
      MEILISEARCH_INDEX_KEY: ${{ secrets.MEILISEARCH_INDEX_KEY }}
      MEILISEARCH_SEARCH_KEY: ${{ secrets.MEILISEARCH_SEARCH_KEY }}
      MEILISEARCH_HOST_URL: ${{ secrets.MEILISEARCH_HOST_URL }}
      ADOBE_ANALYTICS_URL: ${{ secrets.ADOBE_ANALYTICS_URL }}

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: install dependencies
        run: |
          sudo apt update -y
          sudo apt-get install -y graphviz fonts-freefont-ttf
          pip3 install -U pip
          pip3 install -U gsutil==5.27 'pyOpenSSL<24.3.0'
          pip3 install --ignore-installed -r requirements.txt

      - name: Add latest Fioctl docs
        run: |
          export fv=$(wget -q -O- https://api.github.com/repos/foundriesio/fioctl/releases/latest | grep tag_name | sed -E 's/.*"([^"]+)".*/\1/')
          wget -O /tmp/fioctl https://github.com/foundriesio/fioctl/releases/download/${fv}/fioctl-linux-amd64
          chmod +x /tmp/fioctl
          /tmp/fioctl gen-rst source/appendix/fioctl-command-reference/

      - name: Build docs
        run: |
          mkdir out
          make MP_UPDATE_VERSION="dev" OUTDIR='pwd'/out SPHINXBUILD=sphinx-build html

      - name: prepare docs for upload
        run: |
          mv out/html out/dev
          cd out
          tar -czf offline-docs.tgz dev/
          mv offline-docs.tgz dev/

      - name: publish docs
        run: |
          gsutil config -e ${{ secrets.BUCKET_CREDS }}
          gsutil -m rsync -d -r dev gs://docs.foundries.io/dev
